"""`pg slo ...` (M2.8): measure the service levels defined in docs/SLO.md.

- `pg slo probe` calls the API's `/readyz` every few seconds during a test window and appends
  one JSON line per probe to a file.
- `pg slo report` computes the service levels from stored validations and jobs (DATABASE_URL)
  and from probe files. With `--write` it saves a Markdown report that names the validation IDs
  and probe files it came from (CLAUDE.md rule 2: no number typed by hand).
"""

from __future__ import annotations

import time
from datetime import UTC, datetime
from pathlib import Path
from typing import Annotated

import httpx
import typer
from sqlalchemy import select

from pg_cli.settings import Settings
from pg_core.slo import DeviceJob, Probe, SloReport, ValidationTiming, report
from pg_db.models import Build, Job, Validation
from pg_db.session import make_engine, session_scope

app = typer.Typer(help="Service levels (docs/SLO.md).", no_args_is_help=True)
RESULTS = Path("docs/results/phase2")


@app.command("probe")
def probe(
    url: Annotated[str, typer.Option(help="The API's base URL.")],
    out: Annotated[Path, typer.Option(help="JSON-lines file to append to.")],
    interval: Annotated[float, typer.Option(help="Seconds between probes.")] = 30.0,
    minutes: Annotated[float, typer.Option(help="Stop after this long (0 = until Ctrl+C).")] = 0,
) -> None:
    """Probe /readyz until stopped, one line per probe: time, ok, HTTP status, latency."""
    out.parent.mkdir(parents=True, exist_ok=True)
    deadline = time.monotonic() + minutes * 60 if minutes else None
    target = url.rstrip("/") + "/readyz"
    with httpx.Client(timeout=30) as client, out.open("a", encoding="utf-8") as handle:
        while deadline is None or time.monotonic() < deadline:
            started = time.monotonic()
            at = datetime.now(UTC)
            try:
                status: int | None = client.get(target).status_code
            except httpx.HTTPError:
                status = None
            ms = round((time.monotonic() - started) * 1000, 1)
            record = Probe(at=at, ok=status == 200, status=status, ms=ms)
            handle.write(record.model_dump_json() + "\n")
            handle.flush()
            typer.echo(f"{at:%H:%M:%S} {status} {ms} ms")
            time.sleep(max(0.0, interval - (time.monotonic() - started)))


def load(validation_ids: list[int], probe_files: list[Path]) -> SloReport:
    url = Settings().database_url
    if url is None:
        raise typer.BadParameter("DATABASE_URL is not set")
    timings: list[ValidationTiming] = []
    jobs: list[DeviceJob] = []
    with session_scope(make_engine(url.get_secret_value())) as s:
        for vid in validation_ids:
            v = s.get(Validation, vid)
            if v is None:
                raise typer.BadParameter(f"no validation {vid}")
            build = s.get_one(Build, v.build_id)
            timings.append(
                ValidationTiming(
                    validation_id=v.id,
                    features=tuple(v.features),
                    n=v.n,
                    status=v.status,
                    build_registered_at=build.created_at,
                    requested_at=v.created_at,
                    finished_at=v.finished_at,
                )
            )
            for job in s.execute(
                select(Job).where(
                    Job.validation_id == vid, Job.type.in_(("INSTALL_BUILD", "RUN_TEST"))
                )
            ).scalars():
                jobs.append(DeviceJob(status=job.status, attempts=job.attempts))
    probes = [
        Probe.model_validate_json(line)
        for path in probe_files
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    return report(timings, probes, jobs)


def render(r: SloReport, validation_ids: list[int], probe_files: list[Path]) -> str:
    def pct(value: float | None) -> str:
        return "not measured" if value is None else f"{value * 100:.2f}%"

    def mins(value: float | None) -> str:
        return "not measured" if value is None else f"{value} min"

    lines = [
        "# Phase 2 service levels (measured)",
        "",
        f"Generated by `pg slo report` on {datetime.now(UTC):%Y-%m-%d %H:%M} UTC from validations "
        f"{', '.join(str(v) for v in validation_ids)}"
        + (f" and probe files {', '.join(p.name for p in probe_files)}" if probe_files else "")
        + ". Definitions: docs/SLO.md.",
        "",
        "| Service level | Measured |",
        "|---|---|",
        f"| Time from validation request to verdict, median | {mins(r.verdict_p50)} "
        f"({r.finished} of {r.validations} validations finished) |",
        f"| Time from validation request to verdict, worst | {mins(r.verdict_max)} |",
        f"| Time from build registration to verdict, per validation | "
        f"{', '.join(f'{m} min' for m in r.registration_minutes) or 'not measured'} |",
        f"| API availability during the test window | {pct(r.availability)} "
        f"({r.probes_ok} of {r.probes} probes answered 200) |",
        f"| Device jobs that succeeded (product failures count as success) | "
        f"{pct(r.device_job_success)} ({r.device_jobs_ok} of {r.device_jobs}, "
        f"{r.device_attempts} attempts) |",
        "",
        "Per validation (request to verdict): "
        + (", ".join(f"{m} min" for m in r.verdict_minutes) or "none finished"),
        "",
    ]
    return "\n".join(lines)


@app.command("report")
def report_cmd(
    validation: Annotated[list[int], typer.Option(help="Validation id (repeat).")],
    probes: Annotated[list[Path] | None, typer.Option(help="Probe file (repeat).")] = None,
    write: Annotated[bool, typer.Option(help="Save under docs/results/phase2/.")] = False,
) -> None:
    """Compute the service levels from stored validations and probe files."""
    files = list(probes or [])
    text = render(load(list(validation), files), list(validation), files)
    typer.echo(text)
    if write:
        RESULTS.mkdir(parents=True, exist_ok=True)
        path = RESULTS / f"slo_v{'_'.join(str(v) for v in validation)}.md"
        path.write_text(text, encoding="utf-8", newline="\n")
        typer.echo(f"wrote {path}")
