"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-07 23:35:50.895163
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bugs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("flag", sa.String(length=64), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("feature", sa.String(length=64), nullable=False),
        sa.Column("split", sa.String(length=16), nullable=False),
        sa.Column("pages", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.CheckConstraint("split IN ('dev', 'holdout')", name="bugs_split"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("flag"),
    )
    op.create_table(
        "builds",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("apk_sha256", sa.String(length=64), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("locator_tag", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("apk_sha256"),
    )
    op.create_table(
        "specs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("spec_id", sa.String(length=32), nullable=False),
        sa.Column("feature", sa.String(length=64), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("file_sha", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("spec_id"),
    )
    op.create_table(
        "generation_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("build_id", sa.BigInteger(), nullable=False),
        sa.Column("feature", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("prompt_hash", sa.String(length=64), nullable=False),
        sa.Column("temperature", sa.Double(), nullable=True),
        sa.Column("seed", sa.BigInteger(), nullable=True),
        sa.Column("seed_supported", sa.Boolean(), nullable=True),
        sa.Column("n_requested", sa.Integer(), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("llm_calls", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["build_id"],
            ["builds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "candidates",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("generation_run_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("intent", sa.Text(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("code_sha", sa.String(length=64), nullable=False),
        sa.Column("spec_ids", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("pages_used", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("trust_score", sa.Integer(), nullable=True),
        sa.Column("reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("gates", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("human_decision", sa.String(length=16), nullable=True),
        sa.Column("human_reason", sa.Text(), nullable=True),
        sa.Column("human_decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IN ('pending', 'accept', 'review', 'reject')", name="candidates_decision"
        ),
        sa.ForeignKeyConstraint(
            ["generation_run_id"],
            ["generation_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("generation_run_id", "code_sha", name="candidates_run_code"),
    )
    op.create_table(
        "suite_tests",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("code_sha", sa.String(length=64), nullable=False),
        sa.Column("spec_ids", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("accepted_from_candidate_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "origin IN ('human', 'generated', 'repaired')", name="suite_tests_origin"
        ),
        sa.CheckConstraint("status IN ('active', 'quarantined')", name="suite_tests_status"),
        sa.ForeignKeyConstraint(
            ["accepted_from_candidate_id"],
            ["candidates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path"),
    )
    op.create_table(
        "executions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("candidate_id", sa.BigInteger(), nullable=True),
        sa.Column("suite_test_id", sa.BigInteger(), nullable=True),
        sa.Column("build_id", sa.BigInteger(), nullable=False),
        sa.Column("run_group", sa.String(length=64), nullable=False),
        sa.Column("flags", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("purpose", sa.String(length=16), nullable=False),
        sa.Column("repeat", sa.Integer(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("failure_kind", sa.String(length=32), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("wall_ms", sa.Integer(), nullable=False),
        sa.Column("artifacts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("purpose IN ('clean', 'bug', 'benchmark')", name="executions_purpose"),
        sa.CheckConstraint(
            "(candidate_id IS NULL) <> (suite_test_id IS NULL)", name="executions_one_subject"
        ),
        sa.ForeignKeyConstraint(
            ["build_id"],
            ["builds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["suite_test_id"],
            ["suite_tests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "run_group",
            "candidate_id",
            "suite_test_id",
            "flags",
            "repeat",
            "attempt",
            name="executions_idempotent",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_table(
        "kills",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_group", sa.String(length=64), nullable=False),
        sa.Column("candidate_id", sa.BigInteger(), nullable=True),
        sa.Column("suite_test_id", sa.BigInteger(), nullable=True),
        sa.Column("bug_id", sa.BigInteger(), nullable=False),
        sa.Column("killed", sa.Boolean(), nullable=False),
        sa.Column("unstable", sa.Boolean(), nullable=False),
        sa.Column("evidence_execution_ids", postgresql.ARRAY(sa.BigInteger()), nullable=False),
        sa.CheckConstraint(
            "(candidate_id IS NULL) <> (suite_test_id IS NULL)", name="kills_one_subject"
        ),
        sa.ForeignKeyConstraint(
            ["bug_id"],
            ["bugs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["suite_test_id"],
            ["suite_tests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "run_group",
            "candidate_id",
            "suite_test_id",
            "bug_id",
            name="kills_idempotent",
            postgresql_nulls_not_distinct=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("kills")
    op.drop_table("executions")
    op.drop_table("suite_tests")
    op.drop_table("candidates")
    op.drop_table("generation_runs")
    op.drop_table("specs")
    op.drop_table("builds")
    op.drop_table("bugs")
    # ### end Alembic commands ###
